# Generated by Django 3.0.7 on 2020-07-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200712_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
